#EMPLOID CONSTANTS
DETECTION_MODE_REGULAR=0
DETECTION_MODE_TEMPLATE_MATCHING=1
SETTINGS_USE_SELENIUM=1
SETTINGS_USE_APPIUM=2
SETTINGS_USE_PYAUTOGUI=3
APPIUM_PATH=""
APPIUM_SERVER_URL="http://localhost:4723"
APPIUM_COMMAND_EMULATOR_START=r''
APPIUM_SERVER_EXE="appium_server.py"
BROWSER_TYPE_CHROME=0
BROWSER_TYPE_FIREFOX=1
BROWSER_TYPE_TOR=2
USE_HEADLESS=False
REQUEST_DELAY=0
USE_VPN=False
USE_INCOGNITO=False

#database constants
DATABASE_NAME=""
DATABASE_SERVER=""
DATABASE_USER_NAME=""
DATABASE_USER_PASSWORD=""
DATABASE_ENGINE="sqlserver"