from modules.scribe.scribe import Scribe

scribe = Scribe()
scribe.new_page("emploid report")

scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
scribe.insert_row("0", "run chrome", "True", "True", "btn-success")
